### ISSUE TITLE
Question: 'NullPointerException' with Children's Books dataset

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/europeana-cc-lod#10]
@nfreire When I run the crawler using the command underneath...

```
docker-compose run --rm crawler /bin/bash ./crawler.sh \
    -dataset_uri http://data.bibliotheken.nl/id/dataset/rise-childrensbooks \
    -output_file /opt/europeana_cc_lod_share/crawled/centsprenten.nt \
    -log_file run.log
```
...I get a 'java.lang.NullPointerException':

```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	at eu.europeana.commonculture.lod.crawler.LinkedDataCrawler.crawl(LinkedDataCrawler.java:69)
	at eu.europeana.commonculture.lod.crawler.CommandLineInterface.main(CommandLineInterface.java:59)
```

Do you know what the cause of this exception could be?

**Comment by nfreire** [comment]
The children's books collection as was the first LOD delivered to Europeana by the KB. It was the first experiment with an LOD dataset description. After working on it, we evolved on the dataset descriptions for the other two KB collections.
The children's books dataset RDF description is outdated and no longer conforms with the Europeana guidelines.
Could the KB update it?

Regardless of the KB updated the data, I'll change the crawler so that it does not break in such situations.

**Comment by nfreire** [comment]
Should be fixed now, and the crawler no longer throws the exception on an invalid dataset description.

**Comment by sdevalk** [comment]
Thank you!

**Comment by sdevalk** [comment]
Question: if the crawler returns an error on an invalid dataset description, it doesn't seem to exit. My console keeps outputting the following until I shut down the crawler myself:

```
com.ontologycentral.ldspider.http.internal.CloseIdleConnectionThread run
INFO: Closing expired and idle connections
```

Would it be possible to exit the crawler automatically?
