### ISSUE TITLE
shared subdir 'crawled' is expected but not created 

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/europeana-cc-lod#6]
The examples in the crawler and the converter Readme expect a subdirectory 'crawled' within the 'europeana_cc_lod_share' where harvested data is stored and read from. This creates a fatal error running the crawler example.

**Comment by sdevalk** [comment]
@nfreire Can you take a look at this issue?

When running the crawler with the command underneath...

```
docker-compose run --rm crawler /bin/bash ./crawler.sh \
    -dataset_uri http://data.bibliotheken.nl/id/dataset/rise-centsprenten \
    -output_file /opt/europeana_cc_lod_share/crawled/centsprenten.nt \
    -log_file run.log
```

...the crawler exits with a 'failure'...

```
stackTrace:
java.io.FileNotFoundException: /opt/europeana_cc_lod_share/crawled/centsprenten.nt (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at java.base/java.io.FileWriter.<init>(Unknown Source)
	at eu.europeana.commonculture.lod.crawler.LinkedDataCrawler.crawl(LinkedDataCrawler.java:76)
	at eu.europeana.commonculture.lod.crawler.CommandLineInterface.main(CommandLineInterface.java:59)
```

...if the destination directory (in this example: `/opt/europeana_cc_lod_share/crawled`) does not exist. Can the crawler first check whether the directory exists - and if not, create it?

**Comment by nfreire** [comment]
Directories are now checked beforehand by the crawler and created if necessary.

**Comment by sdevalk** [comment]
Excellent, thank you! I'm going to close this issue.
